### ISSUE TITLE
Bug: Not working with HomeAssistant 2022.3.0b0

### ISSUE THREAD

**Issue by n00bcodr** [JurajNyiri/HomeAssistant-Tapo-Control#145]
**Describe the bug**
tapo_control won't setup with HomeAssistant 2022.3.0b0

**To Reproduce**
Steps to reproduce the behavior: Update to HomeAssistant 2022.3.0b0

**Expected behavior**
tapo_control should setup.

**Log**
Couldn't get any debug logs.

```

```

**Camera (please complete the following information):**
 - C100 & C200

**Using stream component**
No

**Camera works through onvif component OR different cameras work in general**
Yes

**Camera has all attributes filled out properly in developer tools**
N/A

**HASS Environment**
Docker

**Additional context**
N/A

**Comment by JurajNyiri** [comment]
Is there any error message in the logs?

**Comment by n00bcodr** [comment]
Enabled debug logs, was not logging anything.

Only error is this.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/49611451/155499133-a680c801-2f68-47a3-97e1-c8362b7bf6c3.png">

**Comment by JurajNyiri** [comment]
Click on logs, see what exactly is in there.

**Comment by JurajNyiri** [comment]
I just tested integration in 2022.3.0b0 and it works flawlessly. Make sure to include logs next time when reporting issue please.

**Comment by erifre** [comment]
I'm having the same problem. Seem to be a problem with a dependency.

2022-02-24 12:25:56 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package onvif-zeep-async==1.0.0: warning: missing-index-doctype
× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://wheels.home-assistant.io/alpine-3.14/aarch64/
note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
ERROR: Cannot install onvif-zeep-async==1.0.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-02-24 12:25:56 ERROR (MainThread) [homeassistant.setup] Setup failed for tapo_control: Requirements for tapo_control not found: ['onvif-zeep-async==1.0.0'].

**Comment by JurajNyiri** [comment]
@erifre thank you that was very helpful.

Could you please try with 1.4.5 I just released?

**Comment by luisleonardo** [comment]
> 

1.4.5 solved the issue. Thanks :)

**Comment by n00bcodr** [comment]
@JurajNyiri apologies couldn't give you more logs, had multiple issues with the beta. had to roll back to 2022.2.9 :(
