### ISSUE TITLE
No motion binary_sensor

### ISSUE THREAD

**Issue by johannwilken** [JurajNyiri/HomeAssistant-Tapo-Control#338]
### Description

I don't have a binary_sensor for motion anymore

### Reproduction Steps

no binary_sensor entity under device entities

### Expected behavior

I don't have a binary_sensor for motion anymore

### If applicable, add error logs.

No errors in logs

### Device Firmware

1.0 (1.3.6)

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Proxmox VM

### Search for similar issues

Yes

### Additional information

Binary_sensor was removed round about core version 2023.4

**Comment by JurajNyiri** [comment]
Firmware 1.3.6 has broken pull endpoint, thanks to new version webhooks can be used which still work.

Check faq for information.
- If you have webhooks enabled, and your Home Assistant internal URL is reachable on HTTP, make sure camera can reach it. 
- Make sure you have correct IP set for Home Assistant. Turn on Advanced Mode under `/profile`. Go to `/config/network` and under `Network Adapter` verify correct IP is shown for the device. If it is not correct, under `Home Assistant URL` uncheck `Automatic` next to `Local Network` and set it to `http://<some IP address>:8123`. **DO NOT USE HTTPS**.
- Certain camera firmwares have pullpoint broken, with only webhooks working. If you are not able to run webhooks because of above (https, or vlan setup), binary sensor will never show up.
- Try walking in front of the camera
