### ISSUE TITLE
Feature Request: Add option to toggle webhooks

### ISSUE THREAD

**Issue by sshalyminov** [JurajNyiri/HomeAssistant-Tapo-Control#347]
**Is your feature request related to a problem? Please describe.**
I have several cams in areas with non-stable WiFi coverage. Old sensors works flaveousely, new ones stuck in "on" state time to time. Looks like camera's FW does not retry WebHook requests in a case it fails - and this is not IP issue. Cams in area near of hotspots works fine. And if I take "failed" cams in those areas - they work fine too. But I need them to work as they had work before 5.2.0

**Describe the solution you'd like**
Please return back old motion sensor behaviour (before 5.2.0) as an option to have a choice how to process them.

**Describe alternatives you've considered**
I don't have alternatives now. To purchase new hotspots and install them is not a option - too expensive just for cams.

**Additional context**
None

**Comment by macbih** [comment]
@sshalyminov, for a workaround you may want to try the cell motion detection sensor. See https://community.home-assistant.io/t/custom-component-tapo-cameras-control/231795/811?u=mibane.

**Comment by JurajNyiri** [comment]
This integration uses upstream onvif with additional improvements. 

I will keep this open in order to add an option to enable/disable webhooks as many users have issues with them and cameras are buggy when both webhooks and pullpoint is open.

It is all described in [FAQ](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#troubleshooting--faq).

**Comment by JurajNyiri** [comment]
Added in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.2.3.
