### ISSUE TITLE
Update is shown although the update was already applied

### ISSUE THREAD

**Issue by stefangries** [JurajNyiri/HomeAssistant-Tapo-Control#411]
### Description

Home Assistant sometimes shows an update for a tapo camera, although the update was already applied.

![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/10342151/2ab4f326-89ba-487d-843d-c8fc9d510c85)

### Reproduction Steps

Go to Home Assistant Settings after applying an update.

### Expected behavior

Home Assistant shouldn't show the update and shouldn't notify me to install the update.

### Device Firmware

1.3.7 Build 230823 Rel.55314n

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HAOS on Intel NUC

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
I spent the whole day trying to fix this, and it should be now fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/3.8.5, but I ran out of cameras to update.

- There was a bug in integration if both motion detection and time sync were disabled, firmware upgrade information was not being pulled
- There was a missing trigger for update entity, so it was not receiving uptodate data about firmware
- There was a missing trigger to update Device information in HA after successful firmware upgrade
- Some cameras report that update is not happening, if it is, resulting previously instantaneous completion as can be seen above

If the issue persists, please let me know and we can reopen this. Make sure to provide debug logs from 3.8.5.

Note: There is an extreme edge case, where after updating you might be seeing 500 errors and need to restart HA. This happens when updating from **really** old firmware (2022, early 2023) to the newest one - I am keeping that in as that would be challenging to fix and it will be less and less probable to happen as time goes on and people update from these old firmwares.
