### ISSUE TITLE
Model C325WB - floodlight scale is from 1-100, instead of 1-5

### ISSUE THREAD

**Issue by sethyx** [JurajNyiri/HomeAssistant-Tapo-Control#521]
### Description

Just wanted to report that C325WB works pretty well with the integration, I tried many control options.
There is one thing where I found some discrepancy, apparently the floodlight scale is from 1-100, instead of 1-5.

### Reproduction Steps

When setting floodlight to maximum (5), it is barely on.

### Expected behavior

Floodlight maximum should be 100 instead of 5.

### Device Firmware

1.1.5 Build 231107 Rel.65795n

### Integration Version

5.4.14

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Docker

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
This will be tricky as some cameras require 1-5 and it looks like some require 1-100. We will need to somehow detect that.

**Comment by JurajNyiri** [comment]
I took another look at this, looking at all the functions we currently have available in pytapo, there is nothing that would show us the range unfortunately. 

The only way how this could be implemented is by a maintaining a list of cameras having this, but I do not like that solution at all, maybe if we are able to find a determining factor, what is different about cameras having 1-100 instead of 1-5...

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.5.0.
