### ISSUE TITLE
cell motion detection not found (Tapo C325WB)

### ISSUE THREAD

**Issue by M4ndaL0re** [JurajNyiri/HomeAssistant-Tapo-Control#537]
### Description

Cell Motion Detection was available.
After Update of this Integration and HA (i did both same time so dont know who caused this) Cell Motion was not available anymore 
"This entity is no longer provided by the Tapo Control integration. If the entity is no longer in use, delete it in the settings."

I used the Cameras on other VLAN, deleted the cameras and readded in the same VLAN as HA is but still same problem, nothing else was changed.

### Reproduction Steps

no

### Expected behavior

Cell motion as Entity available

### If applicable, add error logs.

Dont know if it belongs to:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tapo_control
Quelle: custom_components/tapo_control/utils.py:1234
Integration: Tapo: Kamerasteuerung (Dokumentation, Probleme)
Erstmals aufgetreten: 21. März 2024 um 20:48:27 (1 Vorkommnisse)
Zuletzt protokolliert: 21. März 2024 um 20:48:27

Trying to create motion sensor but motion listener not set up!

### Device Firmware

1.1.14 Build 240131 Rel.44392n

### Integration Version

5.4.17

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

VMWare on Synology

### Search for similar issues

Yes

### Additional information

Sounds like same Issue like #524 but on my side i didnt show up again

i read the FAQ and everything is ok, only one point:
Certain camera firmwares have pullpoint broken, with only webhooks working. If you are not able to run webhooks because of above (https, or vlan setup), binary sensor will never show up.

as i dont know how to activate webhooks on camera

**Comment by JurajNyiri** [comment]
Hi,

make sure camera can reach HA and that HA runs on http, this is most probably a network issue since you mentioned you changed the camera vlan, or the camera simply did not reach out to HA yet.

Follow all steps in FAQ, let it be for a while and move around the camera, it should show up, sometimes it takes a couple of hours.
As an alternative if it does not show up after a few days, you can test using official onvif integration to see if it works there. If it does not work there there is nothing we can do.

You can also try reverting to previous integration version, or HA version and see if it works there to rule out a few factors.

Closing for now as this is most likely not an integration issue, this functionality is very buggy on cameras often.

**Comment by M4ndaL0re** [comment]
i have 3 cameras.
2 in the same VLAN as HA, one in another VLAN. All can reach HA and all Firewall ports are open from HA to VLANs and vise versa.

Good point with prevouis Version, will give it a try
