### ISSUE TITLE
Feature Request: there is no switch to start patrolling pre-configured locations

### ISSUE THREAD

**Issue by coturwood** [JurajNyiri/HomeAssistant-Tapo-Control#546]
**Is your feature request related to a problem? Please describe.**
My camera is C520WS.
It seems to me that there is no way to activate/deactivate patrolling at pre-configured locations.

**Describe the solution you'd like**
Only a switch to perform this action.

**Additional context**
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/157251203/23aeae02-4a4e-4352-ad02-ce9afa5a0177)

**Comment by JurajNyiri** [comment]
My cameras does not have this functionality, please feel free to open new feature request describing how it works. 
Someone will need to discover the call the app makes in order to enable it, or I will need access to the camera. 

I do not remember why this was marked invalid, but the user seems to have closed the issue.

**Comment by enapupe** [comment]
heya

I'm also missing this feature, it would be very helpful to restore patrol mode after I'm taking some automation snapshots
LMK how can I help, I don't mind giving access to the camera. 

FWIW this is similar-ish to the already implemented patrol mode, however in the app you are able to preset camera positions and hovering time on each position. The main missing feature right now is just enabling/disabling this mode.

It's worth noting that this sort of patrolling  could also be accomplished by existing features like `move to preset`, `wait`, `move to preset` (lin an infinite loop). I think I'm not gonna do that automation because it's another failure layer, it's better to have the camera itself managing it.
