### ISSUE TITLE
Feature Request: Update camera status when placed in away mode

### ISSUE THREAD

**Issue by neutrongenious** [JurajNyiri/HomeAssistant-Tapo-Control#56]
Model: Tapo C100

From Tapo App i have changed by camera status to Away mode, which Enables Alarm and notifications

**To Reproduce**
1. Go to Tapo app and place camera in Away mode
2. Go to developer mode and fetch camera data
`access_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
model_name: C100
brand: TP-Link
motion_detection: 'on'
device_type: SMART.IPCAMERA
device_model: C100
device_name: C100 1.0
device_info: C100 1.0
hw_version: '1.0'
sw_version: 1.0.17 Build 201112 Rel.29622n(4555)
device_alias: Entrance
features: '3'
barcode: ''
mac: 3d-80-7A-E7-3E-7E
dev_id: 8021xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
oem_id: EDCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
hw_desc: '4857xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
user: santry
motion_detection_sensitivity: normal
privacy_mode: 'off'
alarm: 'off'
alarm_mode:
  - sound
led: 'on'
day_night_mode: auto
auto_track: null
presets: {}
friendly_name: AntaresIncSantry-Entrance - HD
icon: 'mdi:cctv'
entity_picture: >-
  /api/camera_proxy/camera.antaresincsantry_entrance_hd?token=9576abf49b6a9d423b716b3fa5edc666775eda766e3a2cece04f18fa71da485c
supported_features: 3
`
**Expected behavior**
Status should be updated in HA.

**Log**
**Camera (please complete the following information):**
 - Device Model: [C100]
 - FW: [e.g. 1.0.14 Build 200720 Rel.38552n(4555)]

**Using stream component**
yes

**Camera works through onvif component OR different cameras work in general**
yes

**Camera has all attributes filled out properly in developer tools**
yes

**HASS Environment**
running in docker

**Comment by JurajNyiri** [comment]
This is not currently supported.

Workaround: You can update motion detection, alarm (and more) from Home Assistant side.

**Comment by neutrongenious** [comment]
Can you explain, how to do that?

**Comment by JurajNyiri** [comment]
Yes, check https://github.com/JurajNyiri/HomeAssistant-Tapo-Control#services

For your example, tapo_control.set_alarm_mode and tapo_control.set_motion_detection_mode. You can open those to see all the information related to those services.

You could make an automation, button, switch etc for executing those services. See Home Assistant docs for those. Some examples to get you started are here: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_ENTITIES.md

**Comment by JurajNyiri** [comment]
@neutrongenious where in the app are you setting the away mode?

**Comment by neutrongenious** [comment]
Tried from here.
![image](https://user-images.githubusercontent.com/355154/104464392-28fb5900-55b3-11eb-8378-40b6084e7a7c.png)

**Comment by JurajNyiri** [comment]
Yes that should work, when a motion is detected (if you have motion detection enabled), the camera will start blinking (light = on) and sound an alarm (sound=on) because alarm_mode is on.

Where in the app were you setting away mode?

**Comment by neutrongenious** [comment]
In App main screen:
- Click Camera icon (just avoe Favorites)
- Put camera in Away mode.
that will start Notification and Alarm.

**Comment by JurajNyiri** [comment]
Thank you, I never saw that before.

So what happens is that when you are setting an away or home mode through the app, you are able to automatically set following:
- Motion Detection (and sensitivity)
- Camera alarm (and sound/voice and schedule)

You can do all of these (except alarm schedule) through Home Assistant and a lot more (everything else and more that app doesn't support like auto-track), like moving to preset which the app does not allow with away mode.

Other than that, the camera is doing nothing else, just setting those 2 modes which is suboptiomal.

It is more efficient to create a script (you can have home, vacation, away, sleep, imagination is the limit) in Home Assistant that gives you full control of your camera and can be triggered automatically based on presense sensor as an example.

To reiterate, stting the away mode through the app is just setting motion detection and alarm, not more. 

The attributes of camera (alarm and motion detection) **are** updated when you trigger those modes.

So the solution via Home Assistant does more and there is nothing new in the app that is not supported via HASS. 
Closing this Bug/Feature request because of that.

**Comment by neutrongenious** [comment]
Ok, i will test it.

meanwhile, can you share some preset examples?

**Comment by JurajNyiri** [comment]
Yes, I did above - https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/examples/EXAMPLES_ENTITIES.md

**Comment by neutrongenious** [comment]
Thanks for quick response.
