### ISSUE TITLE
Motion detection stuck C220

### ISSUE THREAD

**Issue by jakobschou** [JurajNyiri/HomeAssistant-Tapo-Control#677]
### Description

I have 4 Tapo cameras updated to the newest firmware, and still have them connected to HA via the guide provided in another issue with work-around to disable Internet access via router.

Livestream and all settings works, but the motion detection is stuck in 'Detected'-state for hours on 2 of the cameras (C220), and no actual updating.
However, I also have C520WS and C210 where the binary sensor Cell Motion works as it should.

I have tried reloading the 2 cameras, restarting HA, and enabling/disabling Internet access without success.

What can I do?

### Reproduction Steps

Binary sensor Cell Motion Detection state is stuck

### Expected behavior

Binary sensor should update regularly based on motion detection

### Device Firmware

Firmware: 1.1.14 Build 240714 Rel.76584n Hardware: 1.0

### Integration Version

5.6.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

vmware virtual machine

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Unfortunately there is nothing we can do as the onvif implementation is buggy on some firmwares. You could try:
1. Official HA onvif integration (make sure to disable this one first) -- if it works reliably there, there is something to fix here. Most likely it won't since this integration reuses most of it.
2. Downgrade firmware
