### ISSUE TITLE
Account temporary_suspension

### ISSUE THREAD

**Issue by RoSulek1** [JurajNyiri/HomeAssistant-Tapo-Control#781]
### Description

![image](https://github.com/user-attachments/assets/7a8a80b6-4048-4fb5-bfbe-997177cf2999)

I went through the path described in the FAQ 3 times for C520WS.

I added deleting the component repository from HACS. All within 2 weeks - so waiting for replication was also included.

The component still either requires a password to Tapo Cloud, or screams with a temporary suspension message (after restarting the camera it asks for a password to the cloud)
More - in the meantime the TP C210 camera, which did not ask for a password to the cloud - started asking for it.
In my opinion, something is still wrong with this whole integration.

I have absolutely no complaints about the author - because he did a gigantic great job - nevertheless it simply does not work.
The fact that subsequent errors are not reported is due to the fact that errors are quickly closed and marked as duplicates.
People for whom it does not work simply waved their hands and gave up.
On ONVIF everything works correctly, so you can live with it.

### Reproduction Steps

1/ go to FAQ
2/ N times repeat steps
still not workin

### Expected behavior

.

### If applicable, add error logs.

there is absolutly NO logs from component

### Device Firmware

1.210. 241025 rel. 55515n

### Integration Version

6.0.1

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

HA Yellow

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
> The component still either requires a password to Tapo Cloud

Cloud password is required as described both in FAQ, Readme and integration itself, for control and it always will be.

> screams with a temporary suspension message

Camera locks itself after too many failed attempts to sign in after entering incorrect password. Restarting camera might help.

> TP C210 camera, which did not ask for a password to the cloud - started asking for it.

Firmware update, every new firmware now requires cloud password for control. Integration support both old firmwares and new, works as expected.

> there is absolutly NO logs from component

Incorrect. Enable debug logs to see more, there are various log levels which you can define for integration (or default) in HA.

> In my opinion, something is still wrong with this whole integration.

There are currently no known technical issues with integration, only people who open issues before reading readme, faq, or what the integration is telling them.

> nevertheless it simply does not work.

In your whole post, you did not specify what doesn't work.

> The fact that subsequent errors are not reported is due to the fact that errors are quickly closed and marked as duplicates.

Issues are reopened if error is valid. In most opened issues users did not read before opening issues, or the suggested FAQ or answer solved their issue, therefore, closed.

> On ONVIF everything works correctly, so you can live with it.

Onvif only exposes RTSP/Onvif functionality, not control.

> Camera has all attributes filled out in developer tools
> Yes

How does it not work then? What does not work? This issue is a lot of generic complaints and no questions.


If you have an issue, follow FAQ first. If you still have an issue, document what you tried, and what happened. Writing "not workin" does not help you, or anyone else. Give this a read - https://community.home-assistant.io/t/how-to-help-us-help-you-or-how-to-ask-a-good-question/114371 .
